FROM resin/rpi-raspbian:jessie

# Install dependencies
RUN apt-get update && apt-get upgrade && apt-get install -y \
    python \
    python-dev \
    python-pip \
    python-virtualenv \
    lirc \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

ADD lirc/hardware.conf  /etc/lirc/hardware.conf
ADD lirc/lirc_options.conf /etc/lirc/lirc_options.conf

RUN echo 'lirc_dev' >> /etc/modules
RUN echo 'lirc_rpi gpio_in_pin=18 gpio_out_pin=17' >> /etc/modules
