"""empty message

Revision ID: 002
Revises: 001
Create Date: 2019-07-23 16:07:09.171086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arduino', sa.Column('radio_channel', sa.Integer(), nullable=True))
    op.add_column('arduino', sa.Column('radio_crc_length', sa.Integer(), nullable=True))
    op.add_column('arduino', sa.Column('radio_data_rate', sa.Integer(), nullable=True))
    op.add_column('arduino', sa.Column('radio_pa_level', sa.Integer(), nullable=True))
    op.add_column('arduino', sa.Column('radio_r_pipe', sa.String(length=10), nullable=True))
    op.add_column('arduino', sa.Column('radio_w_pipe', sa.String(length=10), nullable=True))
    op.add_column('arduino', sa.Column('use_radio', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arduino', 'use_radio')
    op.drop_column('arduino', 'radio_w_pipe')
    op.drop_column('arduino', 'radio_r_pipe')
    op.drop_column('arduino', 'radio_pa_level')
    op.drop_column('arduino', 'radio_data_rate')
    op.drop_column('arduino', 'radio_crc_length')
    op.drop_column('arduino', 'radio_channel')
    # ### end Alembic commands ###
